import Mock from 'mockjs'
export default{
    getMenu:config=>{
        const{userName,password} = JSON.parse(config.body)
        //先判断用户是否存在
        //判断账号和密码是否对应
        if(userName==='admin'&&password==='admin'){
            return {
                code:20000,
                data:{
                    menu:[
                        {
                            path:'/home',
                            name:'home',
                            label:'首页',
                            icon:'s-home',
                            url:'home/index.vue',
                        },
                        {
                            path:'/mall',
                            name:'mall',
                            label:'商品管理',
                            icon:'video-play',
                            url:'mall/index.vue'
                        },
                        {
                            path:'/user',
                            name:'user',
                            label:'用户管理',
                            icon:'user',
                            url:'User/index.vue'
                        },
                        {
                            label:'其他',
                            icon:'location',
                            children:[
                                {
                                    path:'/page1',
                                    name:'page1',
                                    label:'页面1',
                                    icon:'setting',
                                    url:'others/page1.vue'
                                },
                                {
                                    path:'/page2',
                                    name:'page2',
                                    label:'页面2',
                                    icon:'setting',
                                    url:'others/page2.vue'
                                }
                            ]
                        }
                    ],
                    token:Mock.Random.guid(),
                    messgae:'获取成功!'
                }
            }
        }else if(userName==='test'&&password=='test'){
            return{
                code:20000,
                data:{
                    menu:[
                        {
                            path:'/',
                            name:'home',
                            label:'首页',
                            icon:'s-home',
                            url:'home/index'
                        },
                        {
                            path:'/video',
                            name:'video',
                            label:'商品管理',
                            icon:'video-play',
                            url:'mall/index'
                        }
                    ],
                    token : Mock.Random.guid(),
                    messgae:'获取成功！'
                }
            }
        }else{
            return{
                code:-100,
                data:{
                    messgae:'密码错误'
                }
            }
        }
    }
}